### PR TITLE
Updated cname for subdomain routing

### PR DESCRIPTION
**Pull request by shampine**

### CODE REVIEW

**Comment by shampine** [comment]
Thanks for the merge, I see there were some emails and the subdomain was taken down this morning. Feel free to ping me if you want me to put the subdomain back up.

**Comment by shampine** [comment]
My project manager forwarded me the email chain, he should not have taken down this morning. It is back up and functional now and a dig returns:

```
wapro.lbtech.org.	14399	IN	CNAME	lbtech.github.io.
lbtech.github.io.	3599	IN	CNAME	github.map.fastly.net.
github.map.fastly.net.	21	IN	A	199.27.76.133
```

**Comment by mediadoneright** [comment]
sweet. thanks for the commit.  I missed these comments earlier, but seems like we're golden now, ya?

**Comment by shampine** [comment]
Seems alright, if you want Cloudflare enabled for SSL as I know that was a discussion I can move the DNS over in doing so though I will also need to move to the mail forwarding to Mailgun. I'm not sure if it is really needed as this is a static jeykll site. But if desired we can.

**Pull request merged**
