### PR TITLE
Added @gerbz to the lineup for June 18th meetup

### PR DESCRIPTION
**Pull request by gerbz**

### CODE REVIEW

**Comment by gerbz** [comment]
LMK if I did this right... basically my first pull request ever LOL

**Comment by mediadoneright** [comment]
Hey Thanks!  Love that you just went all in ... and the commit itself looks good... but we should chat.  

June 18th is a bit tight for talks, (already have a 3rd not listed -- posted in meetup comments about docker).  However, would you be interested in July 16 meetup?

**Comment by gerbz** [comment]
July is ok - my talk will appeal to developers/engineers as well as sales/marketing people, so it might be nice to have one presentation which appeals to a wider audience =)

**Comment by mediadoneright** [comment]
Will you be at the meetup Thursday?  If so, lets talk details.  

I like to have presentations in the range of 10-20min.  Also, I'd like to get an idea of if you're planning to do a demo or a presentation or ??? I'd really like more of a description ... although the title is intriguing, it is also basically what Zapier website says they do. 

Also to be clear, that's a commitment to make it to the Jul 16 meetup, right?  (It'll be at WE Labs next month)

**Comment by mediadoneright** [comment]
fyi... I added a July skeleton and added the info from your pull request.  You should update your fork and make any changes to the July 16 post.  (it's currently marked as unpublished)

**Comment by gerbz** [comment]
k July 16th it is... tty Thursday

**Comment by mediadoneright** [comment]
:) awesome

**Pull request closed without merging**
